[package]
name = "TUP_problem_remake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.4"
hungarian = "1.1.1"
itertools = "0.13.0"
csv = "1.3.0"
cpu-time = "1.0.0"